### ISSUE TITLE
unity helper for ADGAC

### ISSUE THREAD

**Issue by gpduck** [ru-mii/AutoSplitters#1]
I was playing with using the unity helper from https://github.com/just-ero/asl-help/raw/main/lib/asl-help and was able to get the x/y coordinates from it instead of the memory scanning.

Here's what I came up with if you want to swap it out:

```
startup {
	Assembly.Load(File.ReadAllBytes("Components/asl-help")).CreateInstance("Unity");
}

init {
	vars.lastSplit = 0;
	vars.Helper.TryLoad = (Func<dynamic, bool>)(mono => {
		vars.Helper["Position"] = mono.MakeArray<float>("SaveSystemJ", "playerData", "position");
		return true;
	});
}

split
{
	current.Position[0] //x
	current.Position[1] //y
}
```

I wasn't able to find static references to any of the other values so I don't think they can be pulled in this way :(

**Comment by ru-mii** [comment]
this value is being refreshed every 0.5s and it's no longer used in the autosplitter although it was a good suggestion at some point, thanks
